services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - db
      - redis
    networks:
      - app_network

  db:
    image: postgres:latest
    container_name: db
    restart: always
    ports:
      - "127.0.0.1:5434:5432"
    environment:
      POSTGRES_DB: mg
      POSTGRES_USER: mg
      POSTGRES_PASSWORD: mg
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
